routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('/auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('images', 'ImageController');

Route::resource('tasks', 'TaskController');

Route::resource('news', 'NewsController');

Route::resource('drives', 'DriveController');

Route::resource('notifications', 'NotificationController');

Route::get('profile','HomeController@profile')->name('profile');
Route::post('profile','HomeController@store')->name('profile');

Route::post('profile','HomeController@editdays')->name('editDays');

Route::get('settings','HomeController@settings')->name('settings');
Route::patch('settings','HomeController@settingsStore')->name('settings');

Route::get('layouts/header','HomeController@search')->name('search');

app/Notification.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notification extends Model
{
    protected $fillable = ['title', 'description', 'user_id'];

    public function users()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/NotificationController.php
<?php

namespace App\Http\Controllers;

use App\Notification;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NotificationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $usersWithNotification = User::with('notifications')->get();
        $notifiesWithUsers = Notification::with('users')->get();
        $notifications = Notification::all();


        foreach ($notifications as $one){
            $one->status = 1;
            $one->save();
        }
        return view('notifications.index', compact('usersWithNotification','notifiesWithUsers','notifications'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('notifications.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Auth::user()->role == 'Employee'){
            $newNotify = new Notification();
            $newNotify->title = request('title');
            $newNotify->description = request('description');
            $newNotify->user_id = Auth::user()->id;
            $newNotify->save();
            return redirect()->route('profile');
        } else {
            return back();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $oneNotification = Notification::find($id);

        return view('notifications.edit', compact('oneNotification'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $oneNotification = Notification::find($id);

        $oneNotification->title = request('title');
        $oneNotification->description = request('description');
        $oneNotification->save();

        return redirect('notifications');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Notification::find($id)->delete();

        return redirect('notifications');
    }
}

resources/views/notifications/create.blade.php
@extends ('layouts.header')
@section ('content')

    <form action="{{ route('notifications.store') }}" method="post">
        {{ csrf_field() }}

        <div class="container employees-notification text-center">
            <div class="event-header">
                <div class="clouds">
                    <h2 class="text-center mt-4 font-weight-bold">Create Notification</h2>
                </div>
            </div>
            <div class="row mt-5">
                <div class="container  mt-5 news-title">
                    <div class="row">

                        <div class="col-md-12">
                            <h3>Notification Title</h3>
                            <input type="text" name="title" placeholder="">
                        </div>
                        <div class="col-md-12 mt-5">
                            <h3>Notifications Description</h3>
                            <textarea class="event-description" name="description" type="text"
                                      placeholder=""></textarea>
                        </div>

                    </div>
                    <hr style="border-color: #f8fafc">
                    <button class="create" type="submit">Create
                    </button>
                    <div class="row">
                        <div class="col-md-3 text-center notification-logo">
                            <p>Powered By</p>
                            <img src="/img/cz.png" alt="">
                        </div>
                        <div class="col-md-9 mt-5">
                            <div class="-image">
                                <img src="/img/iceberg.png" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </form>

@endsection

resources/views/notifications/edit.blade.php
@section ('content')
    @extends ('layouts.header')

    <form action="{{ route('notifications.update', ['id' => $oneNotification->id] ) }}" method="post">
        {{ method_field('PATCH') }}
        @csrf

        <br> <br>

        <input name="title" type="text" value="{{ $oneNotification->title }}">
        <br> <br>
        <input name="description"  value="{{ $oneNotification->description }}" placeholder="{{ $oneNotification->description }}">
        <br> <br>
        <button type="submit">Edit</button>


    </form>

    <form action="{{ route('notifications.destroy', ['id' => $oneNotification->id] ) }}" method="post">
        {{ method_field('DELETE') }}
        @csrf
        <button type="submit" >Destroy</button>

    </form>

@endsection

@section ('content')--}}
{{--    @extends ('layouts.header')--}}

{{--    <form action="{{ route('notifications.update', ['id' => $oneNotification->id] ) }}" method="post">--}}
{{--        {{ method_field('PATCH') }}--}}
{{--        @csrf--}}

{{--        <br> <br>--}}

{{--        <input name="title" type="text" value="{{ $oneNotification->title }}">--}}
{{--        <br> <br>--}}
{{--        <input name="description"  value="{{ $oneNotification->description }}" placeholder="{{ $oneNotification->description }}">--}}
{{--        <br> <br>--}}
{{--        <button type="submit">Edit</button>--}}


{{--    </form>--}}

{{--    <form action="{{ route('notifications.destroy', ['id' => $oneNotification->id] ) }}" method="post">--}}
{{--        {{ method_field('DELETE') }}--}}
{{--        @csrf--}}
{{--        <button type="submit" >Destroy</button>--}}

{{--    </form>--}}

{{--@endsection

resources/views/notifications/index.blade.php
@extends ('layouts.header')
@section ('content')

    @csrf

    <div class="container-fluid notification-message">
        <div class="col-md-12 mt-2">


            @foreach($usersWithNotification as $person)
                @foreach($person->notifications as $oneNotification)
                    <div class="row">
                        <div class="col-md-12 mt-5">
                            <p> Author: {{ $person->name}} -- Created: {{ $oneNotification->created_at }}</p>
                        </div>
                    </div>
                    <div class="row messages">
                        <div class="col-md-12">

                            @if(\Illuminate\Support\Facades\Auth::user()->role == 'Manager')
                                {{ Form::open(['method' => 'DELETE', 'route' => ['notifications.destroy', $oneNotification->id]]) }}

                                @csrf
                                {{ method_field('DELETE') }}

                                <button type="submit" class='close mt-3'>X</button>

                                {{ Form::close() }}
                                <h3 class="mt-3"> {{ $oneNotification->title }} </h3>
                            @else

                            @endif
                            <hr>
                            <p>{{ $oneNotification->description }}</p>
                        </div>
                    </div>
                @endforeach
            @endforeach
        </div>
    </div>
@endsection ('content')