routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('/auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('images', 'ImageController');

Route::resource('tasks', 'TaskController');

Route::resource('news', 'NewsController');

Route::resource('drives', 'DriveController');

Route::resource('notifications', 'NotificationController');

Route::get('profile','HomeController@profile')->name('profile');
Route::post('profile','HomeController@store')->name('profile');

Route::post('profile','HomeController@editdays')->name('editDays');

Route::get('settings','HomeController@settings')->name('settings');
Route::patch('settings','HomeController@settingsStore')->name('settings');

Route::get('layouts/header','HomeController@search')->name('search');

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['name', 'description', 'task_date','user_id'];

    public function user_events()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Task;
use App\User;
use Collective\Html\Eloquent\FormAccessible;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TaskController extends Controller
{
    /**
     * TaskController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function index()
    {
        $tasks = Task::all();
        return view('tasks.index', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        if (Auth::user()->role == 'Manager') {

            return view('tasks.create');
        } else {

            return back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Task::create($request->all());
        return redirect()->route('tasks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $thisTask = Task::find($id);
        $author = User::find($thisTask->user_id);

        return view('tasks.show', compact('thisTask', 'author'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::find($id);

        return view('tasks.edit', compact('task'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        if (request('delete') == 'godelete'){

            Task::find($id)->delete();

            return redirect('tasks');
        } else {
            $task = Task::find($id);
            $task->name = request('name');
            $task->description = request('description');
            $task->task_date = request('task_date');
            $task->save();

        }

        return redirect('tasks');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {


        if (request('editButton')){
            redirect(route('tasks.update'));
        }
        Task::find($id)->delete();

        return redirect('tasks');
    }
}

resources/views/tasks/create.blade.php
@extends ('layouts.header')
@section ('content')


    <form action="{{ route('tasks.store') }}" method="post">
        {{ csrf_field() }}


        <div class="container calendar-create-event text-center">
            <div class="event-header">
                <div class="clouds">
                    <h2 class="text-center mt-4 font-weight-bold">Create An Event</h2>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-md-12">
                    <h3>Event Name</h3>
                    <input name="name" type="text" placeholder="Event name" required>
                </div>
                <div class="col-md-12 mt-5">
                    <h3>Event Description</h3>
                    <textarea name="description" class="event-description" type="text" placeholder="Event Description"
                              required></textarea>
                </div>
                <div class="col-md-12 mt-5">
                    <h3>Start Date</h3>
                    <div class="-image">
                        <img src="/img/iceberg.png" alt="">
                    </div>
                    <input type="date" name="task_date" placeholder="" required>
                    <hr style="border-color: #f8fafc">
                    <button class="calendar-button" type="submit">Create</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 text-center setting-logo">
                    <p>Powered By</p>
                    <img src="/img/cz.png" alt="">
                </div>
            </div>
        </div>
        {{--<div class="container  mt-5 news-title">--}}
        {{--<div class="row">--}}
        {{--<div class="col-md-12">--}}
        {{--<h2>Event name: </h2>--}}
        {{--<div class="input-group mb-3">--}}
        {{--<input type="text" class="form-control font-weight-bold" placeholder=""--}}
        {{--name="name"--}}
        {{--aria-label="Username"--}}
        {{--aria-describedby="basic-addon1" required>--}}
        {{--</div>--}}
        {{--</div>--}}
        {{--</div>--}}
        {{--<div class="row">--}}
        {{--<div class="col-md-12">--}}
        {{--<h2>Event description:</h2>--}}
        {{--<textarea rows="7" cols="45" name="description" class="form-control-message"--}}
        {{--placeholder="" required></textarea>--}}
        {{--</div>--}}
        {{--</div>--}}
        {{--<br/><br/>--}}
        {{--Start time: <input type="date" name="task_date" class="form-control font-weight-bold col-md-3" required/>--}}
        {{--<br/><br/>--}}
        {{--<button type="submit" class="btn btn-outline-secondary mt-1">Create Event</button>--}}
        {{--</div>--}}


        {{--    Task name:--}}
        {{--    <br />--}}
        {{--    <input type="text" name="name" />--}}
        {{--    <br />--}}
        <input type="hidden" name="user_id" value="{{ \Illuminate\Support\Facades\Auth::user()->id }}">
        {{--    <br /><br />--}}
        {{--    Task description:--}}
        {{--    <br />--}}
        {{--    <textarea name="description"></textarea>--}}
        {{--    <br /><br />--}}
        {{--    Start time:--}}
        {{--    <br />--}}



        {{--    <br /><br />--}}
        {{--    <input type="submit" value="Save" />--}}


    </form>
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
    <script>
        $('.date').datepicker({
            autoclose: true,
            dateFormat: "yy-mm-dd"
        });
    </script>


@endsection

resources/views/tasks/edit.blade.php
@section ('content')
    @extends ('layouts.header')
    <form action="{{ route('tasks.update', ['id' => $task->id] ) }}" method="post">
        <div class="container calendar-create-event text-center">
            <div class="event-header">
                <div class="clouds">
                    <h2 class="text-center mt-4 font-weight-bold">Edit Event</h2>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-md-12">
                    <h3>Event Name</h3>
                    <input name="name" type="text" value="{{ $task->name }}">
                </div>
                <div class="col-md-12 mt-5">
                    <h3>Event Text</h3>
                    <textarea class="event-description" name="description" type="text"
                              placeholder="">{{ $task->description }}</textarea>
                </div>
                <div class="col-md-12 mt-5">
                    <h3>Event Start Date</h3>
                    <div class="-image">
                        <img src="/img/iceberg.png" alt="">
                    </div>
                    <input type="date" name="task_date" value="{{ $task->task_date }}">
                    <hr style="border-color: #f8fafc">


                        {{ method_field('PATCH') }}
                        @csrf


                    <button name="editButton"  class="calendar-button" type="submit">Edit</button>

                    <button class="calendar-button" name="delete" value="godelete" type="submit">Delete</button>



                </div>


            </div>
            <div class="row">
                <div class="col-md-3 text-center setting-logo">
                    <p>Powered By</p>
                    <img src="/img/cz.png" alt="">
                </div>
            </div>
        </div>
    </form>
    {{--<div class="container news-create-post text-center">--}}
    {{--<div class="event-header">--}}
    {{--<div class="clouds">--}}
    {{--<h2 class="text-center mt-4 font-weight-bold">Edit</h2>--}}
    {{--</div>--}}
    {{--</div>--}}
    {{--<div class="row mt-5">--}}
    {{--<div class="container  mt-5 news-title">--}}
    {{--<div class="row">--}}
    {{--<div class="col-md-12">--}}
    {{--<h3>Event Name</h3>--}}
    {{--<input type="text" name="title" placeholder="" required>--}}
    {{--</div>--}}
    {{--<div class="col-md-12 mt-5">--}}
    {{--<h3>Event Text</h3>--}}
    {{--<input type="text" name="title" placeholder="" required>--}}
    {{--</div>--}}
    {{--<div class="col-md-12 mt-5">--}}
    {{--<div class="-image">--}}
    {{--<img src="/img/iceberg.png" alt="">--}}
    {{--</div>--}}
    {{--<input type="date" name="task_date" placeholder="" required>--}}
    {{--</div>--}}

    {{--</div>--}}
    {{--<div class="row">--}}
    {{--<div class="col-md-3 text-center setting-logo">--}}
    {{--<p>Powered By</p>--}}
    {{--<img src="/img/cz.png" alt="">--}}
    {{--</div>--}}
    {{--</div>--}}
    {{--</div>--}}
    {{--</div>--}}
    {{--</div>--}}


    {{--<form action="{{ route('tasks.update', ['id' => $task->id] ) }}" method="post">--}}
    {{--{{ method_field('PATCH') }}--}}
    {{--@csrf--}}
    {{--<br>--}}

    {{--<input name="name" type="text" value="{{ $task->name }}">--}}

    {{--<br>--}}

    {{--<input name="description" type="text" value="{{ $task->description }}">--}}

    {{--<br>--}}

    {{--<input name="task_date" type="date" value="{{ $task->task_date }}">--}}

    {{--<br>--}}
    {{--<button type="submit">Edit</button>--}}


    {{--</form>--}}
    {{--<form action="{{ route('tasks.destroy', ['id' => $task->id] ) }}" method="post">--}}
{{--    {{ method_field('DELETE') }}--}}
{{--    @csrf--}}
    {{--<button type="submit">Destroy</button>--}}

    {{--</form>--}}

@endsection

resources/views/tasks/index.blade.php
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name') }}</title>

    <!-- Scripts -->
{{--    <script src="{{ asset('js/app.js') }}" defer></script>--}}

<!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">


{{--    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js'></script>--}}
{{--    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.js'></script>--}}


<!-- Styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">


    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
</head>
@if(Auth::check())
    <header class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav mr-auto">

                    <li class="nav-item">
                        <a class="nav-link text-white Profile" href="{{route("profile")}}">Profile</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-white News" href="{{route("news.index")}}">News</a>
                    </li>

                    @if(\Illuminate\Support\Facades\Auth::user()->role == 'Manager')
                        <li class="nav-item">
                            <a class="nav-link text-white Drive" href="{{route("drives.index")}}">Drive</a>
                        </li>

                    @endif

                    <li class="nav-item">
                        <a class="nav-link text-white " href="{{route("settings")}}">Settings</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link text-white " href="{{route("tasks.index")}}">Calendar</a>
                    </li>

                    @if(\Illuminate\Support\Facades\Auth::user()->role == 'Manager')
                        <li class="nav-item">
                            <a class="nav-link text-white " href="{{route("notifications.index")}}">Messages<span

                                    style="color: orange"><sup>

                                            {{ \App\Notification::where('status',0)->count() }}
                                    </sup></span></a>
                        </li>

                    @endif

                </ul>

                @if(\Illuminate\Support\Facades\Auth::user()->role == 'Manager')
                    <form class="form-inline my-2 my-lg-0" method="get" action="{{route('search')}}">
                        @csrf
                        <input class="form-control mr-sm-2" name="search" type="search" placeholder="Search"
                               aria-label="Search">
                        <button class="btn text-white my-2 my-sm-0" style="background-color: #FF8055" type="submit">
                            Search
                        </button>

                    </form>
                @endif
                <button style="background-color: #FF8055" class="btn text-white my-2 m-2 my-sm-0 chemi-logout-btn">
                    <a class="logout_chemi" href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                        {{ __('Logout') }}
                    </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST"
                          style="display: none;">
                        @csrf
                    </form>

                </button>
                @endif
            </div>
        </nav>
    </header>

<form class="text-center" action="{{ route('tasks.index') }}" method="get">
    {{ csrf_field() }}


    <h3 class="text-center mt-5">Calendar</h3>
    @if(\Illuminate\Support\Facades\Auth::user()->role == 'Manager')
        <button class="calendar-button" formaction="{{ route('tasks.create') }}">Create Task</button>
    @endif

    <div id='calendar'></div>

{{--    <img class="calendariceberg" src="img/calendariceberg.jpg">--}}
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.1.0/fullcalendar.min.js'></script>

    <script>
        $(document).ready(function () {
            // page is now ready, initialize the calendar...
            $('#calendar').fullCalendar({
                // put your options and callbacks here
                events: [
                        @foreach($tasks as $task)
                    {
                        title: '{{ $task->name }}',
                        start: '{{ $task->task_date }}',
                        @if(\Illuminate\Support\Facades\Auth::user()->role == 'Manager')
                        url: '{{ route('tasks.edit', $task->id) }}',
                        @else
                        url: '{{ route('tasks.show', $task->id) }}'
                        @endif
                    },
                    @endforeach
                ]
            })
        });
    </script>


</form>

resources/views/tasks/show.blade.php
@extends ('layouts.header')
@section ('content')

    <div class="container news">
        <div class="row">

            <div class="col-md-12 mt-2">
                <div class="news-header-image text-center mt-4">
                    <img class="clouds" src="/img/clouds.png" alt="">
                </div>
                <div class="row mt-5">
                    <div class="col-md-5 news-title">

                        @if(\Illuminate\Support\Facades\Auth::user()->role == 'Manager')

                            <a href="{{ route('tasks.edit', $thisTask->id) }}"><h2

                                    class="font-weight-bold mt-3">{{ $thisTask->name }} </h2></a>
                        @else
                            <h2 class="font-weight-bold mt-3">{{ $thisTask->name }} </h2>
                        @endif
                        <p style="color: #FF8055;" class="ml-2 font-weight-bold mt-4">By {{ $author->name }} </p>
                        <p style="color: #6C757D;" class="ml-3 mt-4">{{ $thisTask->task_date }}</p>
                        {{--<hr class="mt-5">--}}

                    </div>
                </div>
                <div class="row news-text">
                    <div class="col-md-12">
                        <p>{{ $thisTask->description }}</p>
                    </div>
                </div>
            </div>

        </div>
    </div>

{{--    <div class="row mt-5">--}}
{{--        <div class="col-md-5 news-title">--}}
{{--            @if(\Illuminate\Support\Facades\Auth::user()->role == 'Manager')--}}
{{--                <a href="{{ route('news.edit', $one->id) }}"><h2--}}
{{--                        class="font-weight-bold mt-3">{{ $one->title }} </h2></a>--}}
{{--            @else--}}
{{--                <h2 class="font-weight-bold mt-3">{{ $one->title }} </h2>--}}
{{--            @endif--}}
{{--            <p style="color: #FF8055;" class="ml-2 font-weight-bold mt-4">By {{ $person->name }} </p>--}}
{{--            <p style="color: #6C757D;" class="ml-3 mt-4">{{ $one->created_at }}</p>--}}
{{--            --}}{{--<hr class="mt-5">--}}

{{--        </div>--}}
{{--    </div>--}}
{{--    <div class="row news-text">--}}
{{--        <div class="col-md-12">--}}
{{--            <p>{{ $one->description }}</p>--}}
{{--        </div>--}}
{{--    </div>--}}

@endsection