routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('/auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('images', 'ImageController');

Route::resource('tasks', 'TaskController');

Route::resource('news', 'NewsController');

Route::resource('drives', 'DriveController');

Route::resource('notifications', 'NotificationController');

Route::get('profile','HomeController@profile')->name('profile');
Route::post('profile','HomeController@store')->name('profile');

Route::post('profile','HomeController@editdays')->name('editDays');

Route::get('settings','HomeController@settings')->name('settings');
Route::patch('settings','HomeController@settingsStore')->name('settings');

Route::get('layouts/header','HomeController@search')->name('search');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $fillable = ['title', 'description', 'user_id'];

    public function user_events()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Mail\ImportantNews;
use App\News;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use function Sodium\compare;

class NewsController extends Controller
{
    /**
     * NewsController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $usersWithNews = User::with('news')->get();

        $news = News::all();
        return view('news.index', compact('news', 'usersWithNews'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (Auth::user()->role == 'Manager') {

            return view('news.create');
        } else {

            return back();
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        if (Auth::user()->role == 'Manager') {

            $attributes['title'] = request('title');
            $attributes['description'] = request('description');
            $attributes['user_id'] = Auth::user()->id;
            $news = News::create($attributes);

            if (request('emailBroadcast')) {
                foreach (User::all() as $one) {

                    Mail::to($one->email)->queue(
                        new ImportantNews($news)
                    );
                }
            }

            return redirect()->route('news.index');

        } else {
            return back();
        }


    }

    /**
     * Display the specified resource.
     *
     * @param \App\News $news
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $thisNews = News::find($id);

        return view('news.show', compact('thisNews'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\News $news
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $oneNews = News::find($id);

        return view('news.edit', compact('oneNews'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\News $news
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $oneNews = News::find($id);

        $oneNews->title = request('title');
        $oneNews->description = request('description');
        $oneNews->save();

        if (request('delete')){

            $id = request('delete');
            News::find($id)->delete();
        }

        return redirect('news');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\News $news
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        News::find($id)->delete();

        return redirect('news');
    }
}

resources/views/news/create.blade.php
@extends ('layouts.header')
@section ('content')

    <form action="{{ route('news.store') }}" method="post">
        {{ csrf_field() }}

        <div class="container news-create-post text-center">
            <div class="event-header">
                <div class="clouds">
                    <h2 class="text-center mt-4 font-weight-bold">Create New Post</h2>
                </div>
            </div>
            <div class="row mt-5">
                <div class="container  mt-5 news-title">
                    <div class="row">

                        <div class="col-md-12">
                            <h3>Title</h3>
                            <input type="text" name="title" placeholder="" required>
                        </div>
                        <div class="col-md-12 mt-5">
                            <h3>Event Description</h3>
                            <textarea class="event-description" name="description" type="text"
                                      placeholder="" required></textarea>
                        </div>
                        <div class="col-md-12 mt-5">
                            <div class="-image">
                                <img src="/img/iceberg.png" alt="">
                            </div>
                            <label class="check-for-mail">Check For Email Broadcast
                                <input type="checkbox"  name="emailBroadcast">
                                <span class="check-mark"></span>
                            </label>
                            <hr style="border-color: #f8fafc">
                            <button type="submit" class="create"  >Create
                            </button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3 text-center setting-logo">
                            <p>Powered By</p>
                            <img src="/img/cz.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

@endsection


{{--<div class="row">--}}
{{--<div class="col-md-12">--}}
{{--<h2>Description</h2>--}}
{{--<textarea rows="5" cols="45" name="description" class="form-control-message" placeholder=""></textarea><br><br>--}}
{{--<input name="emailBroadcast" type="checkbox" class="">--}}
{{--<label class="form-check-label" for="exampleCheck1">Check For Email Broadcast</label>--}}
{{--</div>--}}
{{--</div>--}}

resources/views/news/edit.blade.php
@section ('content')
    @extends ('layouts.header')

    <div class="container calendar-create-event text-center">
        <form action="{{ route('news.update', ['id' => $oneNews->id] ) }}" method="post">
            @csrf
            {{ method_field('PATCH') }}

            <div class="event-header">
                <div class="clouds">
                    <h2 class="text-center mt-4 font-weight-bold">Edit News</h2>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col-md-12">
                    <h3>News Title</h3>
                    <input name="title" type="text" value="{{ $oneNews->title }}">
                </div>
                <div class="col-md-12 mt-5">
                    <h3>News Description</h3>
                    <textarea class="event-description" name="description" type="text"
                              placeholder="">{{ $oneNews->description }}</textarea>
                </div>

                <div class="col-md-12 mt-5">

                    <div class="-image">
                        <img src="/img/iceberg.png" alt="">
                    </div>
                    <hr style="border-color: #f8fafc">


                    <button name="editButton" class="calendar-button" type="submit">Edit</button>

                    <button class="calendar-button" name="delete" value="{{ $oneNews->id }}" type="submit">Delete</button>


                </div>


            </div>
            <div class="row">
                <div class="col-md-3 text-center setting-logo">
                    <p>Powered By</p>
                    <img src="/img/cz.png" alt="">
                </div>
            </div>
        </form>
    </div>

    {{--<form action="{{ route('news.update', ['id' => $oneNews->id] ) }}" method="post">--}}
    {{--{{ method_field('PATCH') }}--}}
    {{--@csrf--}}

    {{--<br> <br>--}}

    {{--<input name="title" type="text" value="{{ $oneNews->title }}">--}}

    {{--<br> <br>--}}

    {{--<input name="description"  value="{{ $oneNews->description }}" placeholder="{{ $oneNews->description }}">--}}

    {{--<br> <br>--}}
    {{--<button type="submit">Edit</button>--}}


    {{--</form>--}}
    {{--<form action="{{ route('news.destroy', ['id' => $oneNews->id] ) }}" method="post">--}}
    {{--{{ method_field('DELETE') }}--}}
    {{--@csrf--}}
    {{--<button type="submit" >Destroy</button>--}}

    {{--</form>--}}

@endsection

resources/views/news/index.blade.php
@section ('content')
    @extends ('layouts.header')
    <div id='app'></div>
    <form method="get" action="{{route('news.index')}}">
        @csrf
        <div class="container news">
            <div class="row">
                <div class="col-md-12 mt-2">
                    <div class="news-header-image text-center mt-4">
                        <div class="clouds">
                            <h2 class="mt-4">News And Announcements</h2>
                            @if(\Illuminate\Support\Facades\Auth::user()->role == 'Manager')
                                <button class="news-post" formaction="{{ route('news.create') }}">Create New Post
                                </button>
                            @endif
                        </div>
                    </div>
                    @foreach($usersWithNews as $person)
                        @foreach($person->news as $one)
                    <div class="row mt-5">
                        <div class="col-md-5 news-title">
                                    @if(\Illuminate\Support\Facades\Auth::user()->role == 'Manager')
                                        <a href="{{ route('news.edit', $one->id) }}"><h2
                                                class="font-weight-bold mt-3">{{ $one->title }} </h2></a>
                                    @else
                                        <h2 class="font-weight-bold mt-3">{{ $one->title }} </h2>
                                    @endif
                                    <p style="color: #FF8055;" class="ml-2 font-weight-bold mt-4">By {{ $person->name }} </p>
                                    <p style="color: #6C757D;" class="ml-3 mt-4">{{ $one->created_at }}</p>
                                    {{--<hr class="mt-5">--}}

                        </div>
                    </div>
                    <div class="row news-text">
                        <div class="col-md-12">
                            <p>{{ $one->description }}</p>
                        </div>
                    </div>

                    @endforeach
                    @endforeach


                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/news/show.blade.php
@section ('content')
    @extends ('layouts.header')

    <div class="container news">
        <div class="row">
            <div class="col-md-12 mt-2">
                <div class="news-header-image text-center mt-4">
                    <img src="/img/cz.png" alt="">
                    <img class="clouds" src="/img/clouds.png" alt="">
                </div>
                <h2 class="mt-4">Important News</h2>
                <p class="font-weight-bold"> {{ $thisNews->created_at }}</p>
                <p class="font-weight-bold mt-5">{{ $thisNews->title }}</p>
                <p class="mb-3"> {{ $thisNews->description }} </p>
                <hr class="mt-5">
            </div>
        </div>
    </div>
@endsection